name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # مرحله جدید: فایل config.json را قبل از ساخت ایمیج ایجاد می‌کند
      - name: Create config.json from secret
        run: |
          mkdir -p config
          echo "${{ secrets.CONFIG_JSON }}" > config/config.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/dds-nodex:latest # <-- این خط را چک کنید که درست باشد
